---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-worker
  namespace: appflowy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appflowy-worker
  template:
    metadata:
      labels:
        app: appflowy-worker
    spec:
      nodeSelector:
        kubernetes.io/hostname: aurora
      containers:
      - name: appflowy-worker
        image: appflowyinc/appflowy_worker:latest
        env:
        # Environment
        - name: RUST_LOG
          value: "info"
        - name: APPFLOWY_WORKER_ENVIRONMENT
          value: "production"
        - name: APPFLOWY_WORKER_IMPORT_TICK_INTERVAL
          value: "30"

        # Database Configuration
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: appflowy-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appflowy-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: appflowy-secrets
              key: POSTGRES_DB
        - name: APPFLOWY_WORKER_DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@appflowy-postgres:5432/$(POSTGRES_DB)"
        - name: APPFLOWY_WORKER_DATABASE_NAME
          value: "appflowy"

        # Redis Configuration
        - name: APPFLOWY_WORKER_REDIS_URL
          value: "redis://appflowy-redis:6379"

        # S3/MinIO Configuration
        - name: APPFLOWY_S3_USE_MINIO
          value: "true"
        - name: APPFLOWY_S3_MINIO_URL
          value: "http://appflowy-minio:9000"
        - name: APPFLOWY_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: appflowy-secrets
              key: APPFLOWY_S3_ACCESS_KEY
        - name: APPFLOWY_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: appflowy-secrets
              key: APPFLOWY_S3_SECRET_KEY
        - name: APPFLOWY_S3_BUCKET
          value: "appflowy"
        - name: APPFLOWY_S3_REGION
          value: "us-east-1"

        # SMTP Configuration (optional)
        - name: APPFLOWY_MAILER_SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: appflowy-secrets
              key: APPFLOWY_MAILER_SMTP_HOST
        - name: APPFLOWY_MAILER_SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: appflowy-secrets
              key: APPFLOWY_MAILER_SMTP_PORT
        - name: APPFLOWY_MAILER_SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: appflowy-secrets
              key: APPFLOWY_MAILER_SMTP_USERNAME
        - name: APPFLOWY_MAILER_SMTP_EMAIL
          valueFrom:
            secretKeyRef:
              name: appflowy-secrets
              key: APPFLOWY_MAILER_SMTP_EMAIL
        - name: APPFLOWY_MAILER_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appflowy-secrets
              key: APPFLOWY_MAILER_SMTP_PASSWORD
        - name: APPFLOWY_MAILER_SMTP_TLS_KIND
          value: "none"

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
