---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-admin-frontend
  namespace: appflowy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appflowy-admin-frontend
  template:
    metadata:
      labels:
        app: appflowy-admin-frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: aurora
      containers:
      - name: admin-frontend
        image: appflowyinc/admin_frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        # Client-side URLs (used by browser JavaScript)
        - name: APPFLOWY_BASE_URL
          value: "https://appflowy.sector7.helloworlddao.com"
        - name: APPFLOWY_GOTRUE_BASE_URL
          value: "https://appflowy.sector7.helloworlddao.com/gotrue"

        # Server-side URLs (used by Next.js server to connect to backend)
        - name: ADMIN_FRONTEND_REDIS_URL
          value: "redis://appflowy-redis:6379"
        - name: ADMIN_FRONTEND_GOTRUE_URL
          value: "http://appflowy-gotrue:9999"
        - name: ADMIN_FRONTEND_APPFLOWY_CLOUD_URL
          value: "http://appflowy-cloud:8000"
        - name: ADMIN_FRONTEND_PATH_PREFIX
          value: "/console"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: appflowy-admin-frontend
  namespace: appflowy
spec:
  selector:
    app: appflowy-admin-frontend
  ports:
  - port: 3000
    targetPort: 3000
    name: http
